name: Update Submodules

on:
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update submodules to latest main branch
        run: |
          git submodule foreach 'git fetch origin main'
          git submodule foreach 'git checkout origin/main'
          git add <submodule_path>
          git commit -m "Update submodule to latest main branch" || echo "No changes to commit"
          git push origin main
